/*
 * WaveSpeed AI API
 * API for generating images using WaveSpeed AI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.wavespeed.openapi.client.api;

import ai.wavespeed.openapi.client.ApiException;
import ai.wavespeed.openapi.client.model.WavespeedAiModelIdPost200Response;
import ai.wavespeed.openapi.client.model.WavespeedAiModelIdPost400Response;
import ai.wavespeed.openapi.client.model.WavespeedAiModelIdPost401Response;
import ai.wavespeed.openapi.client.model.WavespeedAiModelIdPost500Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Disabled
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * Retrieve the result of a prediction
     *
     * This endpoint retrieves the result of a prediction based on the provided request ID. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void predictionsTaskIdResultGetTest() throws ApiException {
        String taskId = null;
        WavespeedAiModelIdPost200Response response = api.predictionsTaskIdResultGet(taskId);
        // TODO: test validations
    }

    /**
     * Generate an image using the specified model
     *
     * This endpoint generates an image based on the provided parameters. The &#x60;model_id&#x60; is a required path parameter specifying the model to use. The request body can contain various key-value pairs to customize the model generation process. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void wavespeedAiModelIdPostTest() throws ApiException {
        String modelId = null;
        Map<String, Object> requestBody = null;
        String webhook = null;
        WavespeedAiModelIdPost200Response response = api.wavespeedAiModelIdPost(modelId, requestBody, webhook);
        // TODO: test validations
    }

}
